### ISSUE TITLE
关于计算机设计大赛

### ISSUE THREAD

**Issue by Lexuse1314** [Jiang-TaiBai/pest-identification#1]
学长您好，很抱歉以这样一种方式打扰您。是这样的，我们今年想参加4C的软件应用开发的移动应用开发类别，想咨询几个关于文档方面的问题。
设计文档的篇幅是越详细越好吗，虽然前面写的不宜长篇大论但还是有点不放心

**Comment by jiang-taibai** [comment]
感谢您的提问，我没参加过很多次，所以以下内容多多少少有点幸存者偏差。
篇幅：文档我们共写了66页，内容最好要显得特别专业
人工智能设计：人工智能使用了公式+流程图的形式阐释
前后端设计：描述前后端我们借助工具生成图片，例如直接用IDEA生成像模像样的时序图。
数据库设计：我们也是中规中矩地把每一个Table在文档中用表格描述了出来，也花了ER图
界面设计：我们使用应用截图，在PPT中用框框和连线介绍了每一部分，最后把PPT截图出来放在文档里
测试报告：测试报告基本上就是套模板了，针对性地根据项目数据写上去
安装与使用：因为项目已经迭代多次，之前就已经写过了安装和使用说明，故直接搬上去了

以上仅是个人经历，仅供参考，建议你多向指导老师要一下往年学长学姐的优秀文档，或者有其他问题也欢迎讨论。

**Comment by Lexuse1314** [comment]
非常感谢学长提供的宝贵经验，不胜感激！还有一点想请教一下，学长提到的66页，是单指大赛所要求必须提交的 **《设计和开发文档》** 的篇幅吗，还是说提交的 **《设计文档》** 中的各部分只是比较简略的版本，提交的文件中还有更详细的版本？如果《设计文档》的篇幅达到了66页，以学长个人的参赛经历来看，主办方提出 **《设计文档》** 的 _篇幅不宜过长_ 的重要性看来还是有待商榷了

**Comment by jiang-taibai** [comment]
我记得4C交的文档不分简略版和详细版，我们交的文档即这份66页的文档。
其实我们拿此项目参加过两次4C

- 2021年因为还没来得及实现，文档也只写了30页，只拿了区域赛三等奖
- 2022年该系统已经是很成熟的项目了，文档写了66页，拿了全国一等奖

当然也许是其他原因才让我们拿了奖，比如赛道竞争小、项目功能丰富完成度高、算法理论充足等。
希望这对你有参考价值。

**Comment by Lexuse1314** [comment]
收到，谢谢学长
